### ISSUE TITLE
[SuperEditor] Passed Scrollable widget could not be found in Scrollable.of() in iOS

### ISSUE THREAD

**Issue by ninogjoni** [superlistapp/super_editor#1004]
Since updating to Flutter 3.7.0 I got this issue:
`Scrollable.of() was called with a context that does not contain a Scrollable widget.
      No Scrollable widget ancestor could be found starting from the context that was passed to Scrollable.of(). This can happen because you are using a widget that looks for a Scrollable ancestor, but no such ancestor exists.
      The context used was:
        IOSDocumentTouchInteractor(dirty, state: _IOSDocumentTouchInteractorState#b2cd9(lifecycle state: initialized, ticker inactive))`
        
This occurs here: super_editor-0.2.3/lib/src/default_editor/document_gestures_touch_ios.dart:1076 (:185)

Can you also reproduce it?

**Comment by angelosilvestre** [comment]
@ngjoni There is a breaking change in `Scrollable.of()` in Flutter 3.7.0.

You could update your dependency to use the `stable` branch from github.

**Comment by ngjoni** [comment]
@angelosilvestre I tried to also use the git for super_editor_markdown, but it did not work:
`super_editor: 
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
      ref: stable
  super_editor_markdown: 
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor_markdown
      ref: stable`
      
    `Because every version of super_editor_markdown from git depends on super_editor from hosted and package depends on super_editor from git, super_editor_markdown from git is forbidden.
So, because editor depends on super_editor_markdown from git, version solving failed.
pub get failed`

I think I'll stay in version 3.3.10 for now

**Comment by Jethro87** [comment]
@ngjoni Add them to `dependency_overrides` as well. Here's what the relevant parts of my `pubspec.yaml` look like:

```
dependencies:
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor_markdown
...
dependency_overrides:
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
      ref: stable
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor_markdown

```
