### ISSUE TITLE
ListenableBuilder duplicate prevents building with flutter stable

### ISSUE THREAD

**Issue by olavemil** [superlistapp/super_editor#1127]
Despite https://github.com/superlistapp/super_editor/pull/880, `_listenable_builder.dart` itself imports flutter, which currently results in a compile error for newly released Flutter stable, 3.10.

Resolved by chaning to `import 'package:flutter/widgets.dart' hide ListenableBuilder;` on line one.

To reproduce:
1. Have the following in `pubspec.yaml` for any app
```
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  super_editor: ^0.2.4
```
2. try building any platform.
3. results in various compile errors 
`Error: 'ListenableBuilder' is imported from both 'package:flutter/src/widgets/transitions.dart' and 'package:super_editor/src/infrastructure/_listenable_builder.dart'`
