### ISSUE TITLE
[SuperEditor] Crashes when `editables` are not in correct order

### ISSUE THREAD

**Issue by raulmabe-labhouse** [superlistapp/super_editor#1505]
I tried to make the simplest editor I could, but instead stayed debugging for half a day why it was crashing. 

I was initializing the editor this way (which didn't seem like an issue):
```dart
    document = MutableDocument(nodes: [ParagraphNode(id: Editor.createNodeId(), text: AttributedText())]);
    composer = MutableDocumentComposer();
    editor = Editor(
      editables: {
        Editor.composerKey: composer,
        Editor.documentKey: document,
      },
      requestHandlers: defaultRequestHandlers.cast(),
      reactionPipeline: defaultEditorReactions.cast(),
    );
```

But whenever I was deleting a node, the line at `_styler_user_selection.dart` L74 (`final node = _document.getNodeById(viewModel.nodeId)!;` was throwing a null type error.

The fix was including the document as an editable **BEFORE** the composer, like this:
```dart
    document = MutableDocument(nodes: [ParagraphNode(id: Editor.createNodeId(), text: AttributedText())]);
    composer = MutableDocumentComposer();
    editor = Editor(
      editables: {
        Editor.documentKey: document,
        Editor.composerKey: composer,
      },
      requestHandlers: defaultRequestHandlers.cast(),
      reactionPipeline: defaultEditorReactions.cast(),
    );
```

This issue is not on the docs, nor should be intended to be use like this.

Also, why does the user needs to include the `document` and the `composer` as `editables`? Should SuperEditor work without these editables? If the answer is not then why SuperEditor does not include them by default?

--- 

I was building a reproducible example but couldn't make it compile...

**pubspec.yaml** 
```yaml
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      ref: stable
      path: super_editor

dependency_overrides:
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_text_layout
      ref: stable

  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: attributed_text
      ref: stable
```

**Compile Error**
```
Error (Xcode): ../../.pub-cache/git/super_editor-1e39961a3c0ab6bc20f32dda3a6e873b9f26e99b/super_editor/lib/src/infrastructure/platforms/mac/mac_ime.dart:149:30: Error: Too many positional arguments: 1 allowed, but 2 found.
```
