### ISSUE TITLE
[SuperTextField] [web] Exception and minLines/maxLines not functioning in release mode

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#164]
@matthew-carroll 

This is currently a blocker to swapping TextField with SuperTextField on our prod app.

Steps to reproduce:

<details>
<summary>pubspec.yaml</summary>

```yaml
name: webtesty

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      ref: main
      path: super_editor
```
</details>

<details>
<summary>pubspec.lock</summary>

```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.6.1"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.3"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  linkify:
    dependency: transitive
    description:
      name: linkify
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  markdown:
    dependency: transitive
    description:
      name: markdown
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.0"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  super_editor:
    dependency: "direct main"
    description:
      path: super_editor
      ref: main
      resolved-ref: b93142b7b51ffde124c12477cce2bf8e2a7a4b8a
      url: "https://github.com/superlistapp/super_editor.git"
    source: git
    version: "0.1.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.4"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
sdks:
  dart: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
```
</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() async {
  runApp(
    const MaterialApp(
      home: Material(child: TextFieldTest()),
    ),
  );
}

class TextFieldTest extends StatelessWidget {
  const TextFieldTest();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(flex: 1, child: Container(color: Colors.blue)),
        DecoratedBox(
          decoration: BoxDecoration(
            border: Border.all(color: Colors.black, width: 1),
          ),
          child: const SuperTextField(
            minLines: 1,
            maxLines: 5,
          ),
        ),
      ],
    );
  }
}
```
</details>

<details>
<summary>flutter doctor</summary>

```$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.1.0-13.0.pre.288, on Mac OS X 10.14.6 18G8022
    darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
[✓] VS Code (version 1.56.0)
[✓] Connected device (2 available)
```
</details>

* Run the app using the following additional args: `--web-renderer html --profile`. (You can also run it with `--release` but debugging the error with minified js code becomes harder.)
* Focus the textfield and start typing
* You will see the following exception:

```
LateInitializationError: Local 'result' has not been initialized.
js_primitives.dart:47     at Object.wrapException (http://localhost:64585/main.dart.js:5957:17)
js_primitives.dart:47     at Object.throwExpression (http://localhost:64585/main.dart.js:5971:15)
js_primitives.dart:47     at RenderObject_debugNeedsLayout__result_get.call$0 (http://localhost:64585/main.dart.js:66514:18)
js_primitives.dart:47     at RenderParagraph.get$debugNeedsLayout (http://localhost:64585/main.dart.js:66057:66)
js_primitives.dart:47     at SelectableTextState.getOffsetAtPosition$1 (http://localhost:64585/main.dart.js:86627:39)
js_primitives.dart:47     at SuperTextFieldScrollviewState._ensureSelectionExtentIsVisibleInMultilineTextField$0 (http://localhost:64585/main.dart.js:87621:25)
js_primitives.dart:47     at SuperTextFieldScrollviewState._ensureSelectionExtentIsVisible$0 (http://localhost:64585/main.dart.js:87574:14)
js_primitives.dart:47     at SuperTextFieldScrollviewState__onSelectionOrContentChange_closure.call$1 (http://localhost:64585/main.dart.js:87750:12)
js_primitives.dart:47     at WidgetsFlutterBinding._invokeFrameCallback$3 (http://localhost:64585/main.dart.js:69832:18)
js_primitives.dart:47     at WidgetsFlutterBinding._invokeFrameCallback$2 (http://localhost:64585/main.dart.js:69841:19)

Another exception was thrown: Instance of 'ErrorSummary'
```
* This also seems to affect new lines. If I hit enter to make a new line, the SuperTextField doesn't grow.

If you run the same app without the `--profile` or `--release` flag, everything works as expected. It appears to be some sort of runtime null exception with a late value. I've started digging into it, but haven't had any luck identifying the cause yet.
