### ISSUE TITLE
Markdown list parsing is not working as expected (issue with `deserializeMarkdownToDocument`)

### ISSUE THREAD

**Issue by manoletre** [superlistapp/super_editor#1711]
**Package Version**
I am using the **stable branch**. Here is how my `pubspec.yaml` looks like:

```
dependencies:
  super_editor:
      git:
        url: https://github.com/superlistapp/super_editor.git
        ref: stable
        path: super_editor
  super_editor_markdown:
      git:
          url: https://github.com/superlistapp/super_editor.git
          ref: stable
          path: super_editor_markdown

dependency_overrides:
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      ref: stable
      path: super_editor
  super_text_layout:
    git:
        url: https://github.com/superlistapp/super_editor.git
        ref: stable
        path: super_text_layout
  attributed_text:
     git:
        url: https://github.com/superlistapp/super_editor.git
        ref: stable
        path: attributed_text
```

When parsing the string below (printed using `jsonEncode` to show where the newLines are) the method `deserializeMarkdownToDocument` is not working as expected
```
The list:\n- Level 1\n   1. Level 2\n      1. Level 3\n         - Sublevel 1\n         - Sublevel 2\n      2. Level 3 again\n   2. Level 2 returning\n2. Level 1 once more\n   - Bullet list\n     - Another bullet\n- Main bullet list\n   - Sub bullet list\n      - Subsub bullet list
```

This should parse a document that looks like this:

- Level 1
   1. Level 2
      1. Level 3
         - Sublevel 1
         - Sublevel 2
      2. Level 3 again
   2. Level 2 returning
2. Level 1 once more
   - Bullet list
     - Another bullet
- Main bullet list
   - Sub bullet list
      - Subsub bullet list

But is parsing a document that looks like this:
<img width="596" alt="image" src="https://github.com/superlistapp/super_editor/assets/8203735/b74d136f-4187-4a22-8588-7b8366e6c59e">

**To Reproduce**
1. Run `deserializeMarkdownToDocument` with the string provided

**Platform**
I have only tried flutter web

**Flutter version**
```
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (2 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Additional context**
This might be related to another list parsing problem I encountered: When parsing strings with lists that have an empty line between them, the content of the list is copied as a paragraph. 

For example, when parsing this string:
```
La distinción entre "prestación de servicios" y "empleo" se relaciona con la naturaleza de la relación laboral o contractual existente entre las partes implicadas - generalmente un trabajador y la empresa o persona que recibe sus servicios. Reflexionemos sobre las diferencias clave entre estos dos conceptos:

- **Relación contractual**: ¿Cómo piensas que difiere la naturaleza del acuerdo contractual entre la prestación de servicios y el empleo?

- **Independencia y subordinación**: En términos de autonomía, ¿cómo crees que se diferencia un empleado de alguien que presta un servicio bajo su propio control?

- **Permanencia y duración del vínculo laboral**: ¿Qué diferencias hay en cuanto a la estabilidad y duración del arreglo entre prestar servicios y estar empleado?

- **Obligaciones fiscales y beneficios**: ¿De qué manera las responsabilidades fiscales y los beneficios como seguros y pensiones varían entre estos dos tipos de acuerdos?

- **Control sobre el trabajo**: ¿Quién tendría más control sobre el trabajo realizado, alguien que presta servicios o un empleado?

Considerar estas preguntas te ayudará a entender mejor las diferencias fundamentales entre la prestación de servicios y la relación de empleo. Además, elementos como la legislación laboral de tu país y las normativas específicas de cada industria juegan un rol importante para definir cada uno de estos términos. ¿Qué otros factores crees que son importantes al distinguir entre prestación de servicios y empleo?
```

The resulting document looks like this:

<img width="771" alt="image" src="https://github.com/superlistapp/super_editor/assets/8203735/39029ccd-fce9-4947-b395-de287463c40d">

The workaround I implemented for this, is simply removing the lines between the lists and converting the above string to this:
```
a distinción entre "prestación de servicios" y "empleo" se relaciona con la naturaleza de la relación laboral o contractual existente entre las partes implicadas - generalmente un trabajador y la empresa o persona que recibe sus servicios. Reflexionemos sobre las diferencias clave entre estos dos conceptos:
- **Relación contractual**: ¿Cómo piensas que difiere la naturaleza del acuerdo contractual entre la prestación de servicios y el empleo?
- **Independencia y subordinación**: En términos de autonomía, ¿cómo crees que se diferencia un empleado de alguien que presta un servicio bajo su propio control?
- **Permanencia y duración del vínculo laboral**: ¿Qué diferencias hay en cuanto a la estabilidad y duración del arreglo entre prestar servicios y estar empleado?
- **Obligaciones fiscales y beneficios**: ¿De qué manera las responsabilidades fiscales y los beneficios como seguros y pensiones varían entre estos dos tipos de acuerdos?
- **Control sobre el trabajo**: ¿Quién tendría más control sobre el trabajo realizado, alguien que presta servicios o un empleado?

Considerar estas preguntas te ayudará a entender mejor las diferencias fundamentales entre la prestación de servicios y la relación de empleo. Además, elementos como la legislación laboral de tu país y las normativas específicas de cada industria juegan un rol importante para definir cada uno de estos términos. ¿Qué otros factores crees que son importantes al distinguir entre prestación de servicios y empleo?
```

I was looking for a similar workaround for lists with multiple levels, but did not find one. 

I am using the method `deserializeMarkdownToDocument` to populate a document with content generated by OpenAI, so I don't have full control over the markdown that is deserialized.
