### ISSUE TITLE
Cant run emulator after installing super editor

### ISSUE THREAD

**Issue by ember11498** [superlistapp/super_editor#1729]
When I run the emulator I get the following error:

`Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
/C:/Users/35191/AppData/Local/Pub/Cache/hosted/pub.dev/super_editor-0.2.6/lib/src/default_editor/text.dart:793:9: Error: No named parameter with the name 'textScaleFactor'.
        textScaleFactor: widget.textScaleFactor ?? MediaQuery.textScaleFactorOf(context),
        ^^^^^^^^^^^^^^^
/C:/Users/35191/AppData/Local/Pub/Cache/hosted/pub.dev/super_text_layout-0.1.8/lib/src/super_text_layout_with_selection.dart:20:3: Context: Found this candidate, but the arguments don't match.
  SuperTextWithSelection.single({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/35191/AppData/Local/Pub/Cache/hosted/pub.dev/super_editor-0.2.6/lib/src/infrastructure/super_textfield/android/android_textfield.dart:535:9: Error: No named parameter with the name 'textScaleFactor'.
        textScaleFactor: MediaQuery.textScaleFactorOf(context),
        ^^^^^^^^^^^^^^^
/C:/Users/35191/AppData/Local/Pub/Cache/hosted/pub.dev/super_text_layout-0.1.8/lib/src/super_text_layout_with_selection.dart:20:3: Context: Found this candidate, but the arguments don't match.
  SuperTextWithSelection.single({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/35191/AppData/Local/Pub/Cache/hosted/pub.dev/super_editor-0.2.6/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:397:9: Error: No named parameter with the name 'textScaleFactor'.
        textScaleFactor: _textScaleFactor,
        ^^^^^^^^^^^^^^^
/C:/Users/35191/AppData/Local/Pub/Cache/hosted/pub.dev/super_text_layout-0.1.8/lib/src/super_text_layout_with_selection.dart:20:3: Context: Found this candidate, but the arguments don't match.
  SuperTextWithSelection.single({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/35191/AppData/Local/Pub/Cache/hosted/pub.dev/super_editor-0.2.6/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart:551:9: Error: No named parameter with the name 'textScaleFactor'.
        textScaleFactor: MediaQuery.textScaleFactorOf(context),
        ^^^^^^^^^^^^^^^
/C:/Users/35191/AppData/Local/Pub/Cache/hosted/pub.dev/super_text_layout-0.1.8/lib/src/super_text_layout_with_selection.dart:20:3: Context: Found this candidate, but the arguments don't match.
  SuperTextWithSelection.single({
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1`

How can I solve this issue?

**Comment by rutvik110** [comment]
Seems like you're using the `super_editor` version hosted on pub.dev which isn't compatible with latest Flutter releases due to some deprecations/changes in the framework. For the time being, would suggest to point to the `super_editor`'s github stable/master channel in pubspec till we can get latest release on pub.dev. 

You can check out the example project pubspec on how it handles this,

```yaml
dependencies:
   super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor_markdown
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_text_layout
```
