### ISSUE TITLE
[BUG] - AttributedTextEditingController.clear() not working as expected

### ISSUE THREAD

**Issue by CillianMyles** [superlistapp/super_editor#2094]
**Package Version**
`SuperTextField` from `super_editor` on latest `main`

**User Info**
Superlist

**To Reproduce**
1. Type some text into a `SuperTextField`
2. Press a button which is hooked up to call `AttributedTextEditingController.clear()`
3. The text is not cleared, and no exception is printed to the console.
4. If you then continue to type text, an exception is printed to the console.

Note: I have found it possible to work around this by instead of calling `.clear()`:

```dart
    _textController.updateTextAndSelection(
      text: AttributedText(),
      selection: const TextSelection.collapsed(offset: 0),
    );
```

The above works fine visually:
* focus still present
* caret still blinking
* new typed text ends up in the text field

... however an exception is printed to the console.

**Minimal Reproduction Code**
If the bug is reproducible in the Example app, you can delete this section. Otherwise, please provide a minimal, runnable code reproduction.

<details>
  <summary>Minimal, Runnable Code Sample</summary>

  ```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:super_editor/super_editor.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Clear Text Field Example',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Clear Text Field Example'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    super.key,
    required this.title,
  });

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _focusNode = FocusNode();
  final _textController = ImeAttributedTextEditingController();

  @override
  void initState() {
    super.initState();

    SchedulerBinding.instance.addPostFrameCallback((_) {
      // Why do I have to request focus in a post frame callback?
      //
      // I guess it's something about the focus node not yet being parented?
      // Other Flutter widgets don't seem to have this issue.
      //
      // Oddly enough if I don't use the post frame callback, the text field
      // takes up all available vertical space, and results in a layout
      // exception.
      _focusNode.requestFocus();
    });
  }

  @override
  void dispose() {
    _focusNode.dispose();
    _textController.dispose();
    super.dispose();
  }

  void _clearTextOption1() {
    // Text is not cleared.
    // No error printed to console.
    // Subsequently typed text does not show in text field, and an exception 
    // is printed to the console.
    _textController.clear();
  }

  void _clearTextOption2() {
    // This works perfectly visually:
    // * focus still present
    // * caret still blinking
    // * new typed text ends up in the text field
    //
    // ... but an exception is printed to the console
    _textController.updateTextAndSelection(
      text: AttributedText(),
      selection: const TextSelection.collapsed(offset: 0),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final textStyle = theme.textTheme.bodyLarge!.copyWith(
      color: theme.colorScheme.primary,
    );
    final hintStyle = textStyle.copyWith(
      color: theme.colorScheme.secondary,
    );

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Align(
        alignment: Alignment.topCenter,
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(
                width: 1,
                color: Theme.of(context).colorScheme.primary,
              ),
              borderRadius: BorderRadius.circular(8),
              color: Theme.of(context).colorScheme.surface,
            ),
            child: Row(
              mainAxisSize: MainAxisSize.max,
              children: [
                const SizedBox(width: 16),
                Expanded(
                  child: SuperTextField(
                    focusNode: _focusNode,
                    textController: _textController,
                    inputSource: TextInputSource.ime,
                    textStyleBuilder: (_) => textStyle,
                    hintBuilder: (_) => Text(
                      'Type something',
                      style: hintStyle,
                    ),
                    hintBehavior: HintBehavior.displayHintUntilTextEntered,
                  ),
                ),
                const SizedBox(width: 16),
                IconButton(
                  icon: const Icon(Icons.clear),
                  onPressed: _clearTextOption1,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
  ```
</details>

**Actual behavior**
When calling `_clearTextOption1`:
- Text is not cleared.
- No error printed to console.
- Subsequently typed text does not show in text field, and an exception is printed to the console.

When calling `_clearTextOption2`:
- This works perfectly visually:
  * Focus is still present.
  * The caret still blinking.
  * Newly typed text ends up in the text field.
- An unexpected error is printed to the console.

**Expected behavior**
When calling `_clearTextOption1`:
- Text should be cleared.
- No error should be printed.
- Focus should still be present.
- The caret should still be blinking.
- Subsequently typed text should end up in the text field, without causing any errors.

When calling `_clearTextOption2`:
- Should have exact results as option 1, without any errors.
- Should not have to use because option 1 doesn't work.

**Platform**
Which device(s) and operating system(s) have experienced the problem?
All of above notes are about iOS.

Just checked macOS and it also suffers from the issues with `.clear()`, but the workaround does not seem to cause any errors to be printed to console.

Did not test on Android or web.

**Flutter version**
```
Flutter 3.22.0-22.0.pre.7 • channel main • https://github.com/flutter/flutter.git
Framework • revision 9f3be7dfd9 (6 weeks ago) • 2024-05-02 04:15:02 -0400
Engine • revision 58b031c096
Tools • Dart 3.5.0 (build 3.5.0-122.0.dev) • DevTools 2.35.0
```

**Screenshots**
Option 1:

https://github.com/superlistapp/super_editor/assets/5852503/b42100a1-cac1-4ce6-a14e-eceda85fba79

Option 2:

https://github.com/superlistapp/super_editor/assets/5852503/ecec124f-cfa9-4281-9240-6ee080ac8bfe

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by angelosilvestre** [comment]
@CillianMyles Is there any other step or setting needed to trigger this issue?

I'm trying to reproduce this issue with the exact flutter version and OS version, but so far I was unable to reproduce it.

https://github.com/superlistapp/super_editor/assets/7597082/ec497835-917c-4838-a1a7-d3bf12b5bbc7

**Comment by CillianMyles** [comment]
Hey @angelosilvestre

So I looked into my sample app setup, and I think I found the cause of all the exceptions: I forgot to override `attributed_text` to point to `main`. 

With the following I get no exceptions:

```yml
name: clear_text_editing_controller
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-122.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  attributed_text:
  super_editor:
  super_text_layout:

dependency_overrides:
  attributed_text:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: attributed_text
      ref: main
  super_editor:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: super_editor
      ref: main
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor_markdown
      ref: main
  super_text_layout:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: super_text_layout
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
```

Which are resolved to:

```
  attributed_text:
    dependency: "direct main"
    description:
      path: attributed_text
      ref: main
      resolved-ref: e4561f8cbebb7b7baa7b6c941d68abc820e44a98
      url: "git@github.com:superlistapp/super_editor.git"
    source: git
    version: "0.3.1"
  super_editor:
    dependency: "direct main"
    description:
      path: super_editor
      ref: main
      resolved-ref: e4561f8cbebb7b7baa7b6c941d68abc820e44a98
      url: "git@github.com:superlistapp/super_editor.git"
    source: git
    version: "0.3.0-dev.1"
  super_editor_markdown:
    dependency: "direct overridden"
    description:
      path: super_editor_markdown
      ref: main
      resolved-ref: e4561f8cbebb7b7baa7b6c941d68abc820e44a98
      url: "https://github.com/superlistapp/super_editor"
    source: git
    version: "0.1.5"
  super_text_layout:
    dependency: "direct main"
    description:
      path: super_text_layout
      ref: main
      resolved-ref: e4561f8cbebb7b7baa7b6c941d68abc820e44a98
      url: "git@github.com:superlistapp/super_editor.git"
    source: git
    version: "0.1.10"
```

---

However I still have the same problem as I see in your video. By calling `_controller.clear()` the text is visually cleared, but the cursor is no longer blinking. When I type text it ends up in the field, but for a second it doesn't look like the field still has focus. Can you see that?
