### ISSUE TITLE
SuperTextField - Exception when rendering BlinkingTextCaret on web 

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#459]
```
$ flutter --version
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (7 days ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

`main.dart`

```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() {
  final controller = AttributedTextEditingController(
    text: AttributedText(text: '🐢'),
  );
  runApp(
    MaterialApp(
      home: Center(
        child: SuperDesktopTextField(textController: controller),
      ),
    ),
  );
}
```

`pubspec.yaml`

```
name: flutter_sandbox
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
      ref: 42aadf8175971931215023b8717231fad1831ae1
```

# Steps to reproduce
* Run `flutter run -d chrome` (Flutter stable 2.10.3)
* Hit tab to focus the TextField (or click on it to manually focus)
* You will get an exception `Bad state: No element` when trying to render `BlinkingTextCaret`

@matthew-carroll we'd be willing to sponsor a fix or workaround for the error above.

The one below isn't a priority for us since it's a specific commit Jan 30th that we just got off of.

# Related issue on later version of Flutter on MacOS or Web
* Use flutter commit `29fd0469ed38e7f81a3e73bbdf06b89907bdba95`
* Run `flutter run -d macos` (or `flutter run -d chrome`)
* Hit tab to focus the TextField (or click on it to manually focus)
* You will the same exception `Bad state: No element` when trying to render `BlinkingTextCaret`
