### ISSUE TITLE
SuperTextField - caret blinks while typing

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#460]
Tried on the latest version of super_editor:

```
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
      ref: 57a7d72166272582cbbdedc752b6f328c0493f88
```

Actual behavior:
When you start typing, the cursor flashes

Expected behavior:
The cursor stays solid while typing

Quick video explaining the issue:
https://www.loom.com/share/9352fc3b1837434696d8af4b2e2c0c39dd

For some reason, the flashing seems a bit more prominent on web.

@matthew-carroll we're happy to sponsor a fix for this
